[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "alpyne"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn",
    "watchgod",
    "aiokafka",
    "aioredis",
    "pynversify"
]
